### PR TITLE
task7

### PR DESCRIPTION
**Pull request by sleepwalky**
Evaluation criteria (each mark includes previous mark criteria)
Provide your reviewers with the link to the repo, client application and URLs to execute the /import path of the import-service

- [x]  1 - authorization-service is added to the repo, has correct basicAuthorizer lambda and correct serverless.yaml file

- [x]  3 - import-service serverless.yaml file has authorizer configuration for the importProductsFile lambda. Request to the importProductsFile lambda should work only with correct authorization_token being decoded and checked by basicAuthorizer lambda. Response should be in 403 HTTP status if access is denied for this user (invalid authorization_token) and in 401 HTTP status if Authorization header is not provided.

- [x]  5 - update client application to send Authorization: Basic authorization_token header on import. Client should get authorization_token value from browser localStorage https://developer.mozilla.org/ru/docs/Web/API/Window/localStorage authorization_token = localStorage.getItem('authorization_token')

Additional (optional) tasks

- [x]  +1 - Client application should display alerts for the responses in 401 and 403 HTTP statuses. This behavior should be added to the nodejs-aws-fe-main/src/index.tsx file

FE: https://d2y9uejo7k6pyr.cloudfront.net/admin/products
FE PR: https://github.com/sleepwalky/nodejs-aws-fe/pull/5
authorization_token = c2xlZXB3YWxreTpURVNUX1BBU1NXT1JE

### CODE REVIEW

**Comment by sleepwalky** [comment]
Ревьюверы, оставьте свои контакты, я вас пингану когда будет готово)

**Comment by skyRoma** [comment]
> Ревьюверы, оставьте свои контакты, я вас пингану когда будет готово)

пингуй когда доделаешь

**Review by skyRoma — CHANGES_REQUESTED** [review]
waiting for solution

**Comment by sleepwalky** [comment]
@skyRoma ready xD

**Review by skyRoma — APPROVED** [review]

**Pull request merged**
